### ISSUE TITLE
Update documents toward next version (1.3.0)

### ISSUE THREAD

**Issue by fukai-t** [RIKEN-RCCS/MilvusVisor#6]
Toward next release, we need to update the document (mainly, README.md).
Especially, the list of tested machiles should be updated (https://github.com/RIKEN-RCCS/MilvusVisor#tested-machines).

@PG-MANA @garasubo , could you tell me your tested devices for recent PRs? Additionally, if you find points to update, please tell me.

**Comment by PG-MANA** [comment]
New Device Support
* BlueFiled2: SMP Boot Only
* Raspberry Pi 4B: SMP Boot Only (Depend on #5 )

**Comment by PG-MANA** [comment]
By #7 and #8 , Raspberry Pi 4 B will be supported(nosmp).
And #5 adds SMP support for Raspberry Pi4.

**Comment by fukai-t** [comment]
Done by #12
